name: 'dna_public_dbt_macros'
version: '1.0.0'
config-version: 2

profile: 'default'

macro-paths: ["macros"]

seeds:
  dna_public_dbt_macros:
    cleanup_exceptions:
      +column_types:
        object_type: varchar(16777216)
        schema_name: varchar(16777216)
        object_name: varchar(16777216)
        comment: varchar(16777216)

## this dbt project is not supposed to do anything
## it's only the place where we store shared macros
